Added in a few fixes, tidied up code base and begun work on additional modules and functionality
knavesec/CredMaster pull request #20
Opened 2022-10-19 14:43 UTC by ZephrFish

2022-10-21 06:19 UTC, knavesec requested changes
Overall looks good, few small changes requested

2022-10-21 06:19 UTC, knavesec commented on README.md
> +4. [Optional] Add your slack webhook URL into config-vars.json if you want to use a webhook for when credentials are successfully guessed!
Remove this line, Notification settings will be passed via CLI (for the time being). Will be making excessive changes to the CLI input process to make this easier

2022-10-21 06:19 UTC, knavesec commented on README.md
> +* [GMailEnum](https://github.com/knavesec/CredMaster/wiki/) - GSuite/Gmail enumeration
Add GmailEnum to the link, small typo

2022-10-21 09:28 UTC, ZephrFish reviewed
Added in requested changes, updated documentation. 

New:
Added AzVault module for spraying
Added MS_Template for creating microsoft/azure specific spraying modules

Updated:
Unified config file so that webhook and aws config in same file, updated utils. credmaster and modules to accommodate.
Added in more details of the change log, work in progress and todo to add transparency to tooling dev.

WIP:
Began work on rewrite of config file to factor in other webhooks
Began research into GCP/Azure alternatives for API gateway and increased opsec

2022-10-21 19:54 UTC, knavesec requested changes
Looking really good, unfortunately I made some changes the same time you did that conflict. See the comments, all content looks good

2022-10-21 19:54 UTC, knavesec commented on README.md
> +4. [Optional] Add in config file as a parameter, containing info of AWS keys, webhooks and other content, template is shown below:
Revert, I added changes to this line with documentation

2022-10-21 19:54 UTC, knavesec commented on README.md
> +	"slack_webhook":"YOURURLHERE",
Remove this section, included a format config file section

2022-10-21 19:54 UTC, knavesec commented on README.md
> +python3 credmaster.py --plugin {pluginname} --config config-vars.json -u userfile -p passwordfile -a useragentfile {otherargs}
Modify to just python3 credmaster.py --config config.json

2022-10-21 19:54 UTC, knavesec commented on README.md
> +python3 credmaster.py --plugin {pluginname} --config config-vars.json -u userfile -p passwordfile -a useragentfile {otherargs}
Since everything can be specified via config file

2022-10-21 19:54 UTC, knavesec commented on README.md
> +* Rewrite of CLI argument handling in favour of config files
Remove since finished

2022-10-21 19:54 UTC, knavesec commented on config-vars.json
> +	"slack_webhook":"YOURURLHERE",
Remove file, created config.json file with requisite information

2022-10-21 19:54 UTC, knavesec commented on credmaster.py
> +from utils.json_helper import read_json
remove, not necessary

2022-10-21 19:54 UTC, knavesec commented on credmaster.py
> +		config_dict = read_json(args.config)
Removed this whole section, key parsing handled in new function

2022-10-21 19:54 UTC, knavesec commented on credmaster.py
> +	if webhook_url is None:
Remove, people may not want to specify a webhook for notifications

2022-10-21 19:54 UTC, knavesec commented on credmaster.py
> +	fp_args.add_argument('--config', type=str, default=None, help='Authenticate to AWS and add in webhooks too plus other config if wanted')
Change to just say something like "config file for all configuration options" or something similar

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +import datetime, requests
Remove datetime, not necessary

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +    ts = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
remove, unused

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +    data_response = {
Edit this to just include used sections, see examples in current plugin updates

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +        # Opsec tip: UA must be edge otherwise Defender for cloud will flag it!
Good note, does this apply to all MS spraying functions? May be good to implement elsewhere?

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +        data_response['code'] = resp.status_code
remove, unused

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +            data_response['success'] = True
change to current plugin style.
data_response['result'] = "success" is the new return (both "result" dict key, and "success" as a string)
Remove coloration from output response, that will be handled outside of plugins themselves

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +            data_response['success'] = True
Remove slack notify functions as well, that will be handled outside of plugin

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +            data_response['success'] = True
Apply these to all the responses below

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +                data_response['2fa_enabled'] = True
remove, unused

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +                data_response['code'] = "2FA Microsoft"
remove, unused

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +                data_response['2fa_enabled'] = True
remove unused

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +                data_response['code'] = "2FA Other"
remove unused

2022-10-21 19:54 UTC, knavesec commented on plugins/azvault/azvault.py
> +                data_response['change'] = True
remove unused

2022-10-21 19:54 UTC, knavesec commented on plugins/template/MS_Template/template.py
> +import datetime, requests
All comments from previous template apply here

Curious if we could make this ultra generic, where you just specify the resource? Picking from vault.azure.net, graph.microsoft.net, etc so there doesn't need to be templates for each

2022-10-21 19:54 UTC, knavesec commented on utils/utils.py
> +config_dict = read_json("config-vars")
Accept changes to current notify function, separated in new file

2022-10-24 15:28 UTC, knavesec commented
Closed for repull due to side conversation

2022-10-24 15:28 UTC, closed without merging