Housecleaning
knavesec/CredMaster pull request #25
Opened 2022-10-28 00:03 UTC by ZephrFish

Updated:
Steamlined code to tidy up format functions and convert to python3 format strings, compressed code and made it more efficient.

Standardised where possible all messages use " instead of '  to make life easier.

Also flipped config file to example and added to .gitignore so we don't commit secrets in testing to git :)

2022-11-07 21:24 UTC, knavesec requested changes
Really appreciate you doing all this work to reformat the strings. Looks like there were some changes (new push) that may not have been replicated in the code that needs to be adjusted, but nothing too major

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +		with open(outfile, 'a+') as file:
Add back in the "-credmaster.txt" addition to the outfile name, used to distinguish between standard outfile and valid user outfile

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +	now = utc_now + datetime.timedelta(hours=offset)
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +utc_now = datetime.datetime.utcnow()
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +		outfile = outfile + "-credmaster.txt"
remove the + "-credmaster" part, this will be added in log functions

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +	start_time = utc_now
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +				next_time = utc_now + datetime.timedelta(hours=weekdaywarrior) + datetime.timedelta(minutes=sleep_time)
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +					log_entry(f"Completed spray with user-pass file {userpass_file} at {utc_now}")
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +					log_entry(f"Completed userenum at {utc_now}")
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +					log_entry(f"Completed spray with password {password} at {utc_now}")
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +				log_entry(f"Completed spray with password {password} at {utc_now}, moving on to next password...")
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +				log_entry(f"Completed spray with password {password} at {utc_now}, sleeping for {delay} minutes before next password spray")
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on credmaster.py
> +	end_time = utc_now
Remove utc_now, else all timestamps will be exactly the same

2022-11-07 21:24 UTC, knavesec commented on plugins/azuresso/azuresso.py
> +            # utils.slacklog("Alert: Username valid but password is not in AzureAD")
remove

2022-11-07 21:24 UTC, knavesec commented on plugins/azuresso/azuresso.py
> -            data_response['valid_user'] = True
add back in

2022-11-07 21:24 UTC, knavesec commented on plugins/azuresso/azuresso.py
> +            # utils.slacklog("Alert: Username valid but password is not in AzureAD")
Do this for all plugins, notifications done outside plugins

2022-11-07 21:24 UTC, knavesec commented on plugins/azuresso/azuresso.py
> -            data_response['valid_user'] = True
Add back in valid user tags for all plugins, used for automated logging of valid users

2022-11-07 21:24 UTC, knavesec commented on plugins/msol/msol.py
> +		'error' : False,
Is it just me or are some of these randomly differently tabbed? Unsure how much that matters

2022-11-07 21:24 UTC, knavesec commented on plugins/template/template.py
> -    # valid_user
Add back in

2022-11-10 00:02 UTC, ZephrFish commented
Shall work on changes, will see if easier to implement into class implementation too

2022-11-10 00:03 UTC, ZephrFish commented on credmaster.py
> +	ts = utc_now.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
the utc_now var is simplified, takes the old value and is assigned it shouldn't change the functionality from my testing

2022-11-10 01:32 UTC, ZephrFish commented
Fixed changes as requested, will work on class re-work once these changes are committed :)

2022-11-10 22:08 UTC, closed without merging